insert into catalogue.medicinal_ingredient (ingredient_id, name, extract_type_desc, source_material)
values  (6526, 'Fruit Blend', 'ND', 'Vaccinium myrtillus - Fruit'),
        (6527, 'Scutellaria baicalensis', 'ND', 'ND'),
        (6528, 'Vitamin E', 'ND', 'ND'),
        (6529, 'Lactobacillus acidophilus', 'ND', 'Whole cell - Lactobacillus acidophilus HA-122'),
        (6530, 'Daphne mezereum', 'ND', 'Bark'),
        (6531, 'Wolfiporia extensa', 'ND', 'ND'),
        (6532, 'Passiflora incarnata', 'ND', 'Herb top'),
        (6533, 'Vitex rotundifolia', 'ND', 'Fruit'),
        (6534, 'L-Glutathione', 'ND', 'L-Glutathione'),
        (6535, 'Calcium', 'ND', 'Whey protein isolate'),
        (6536, 'N-(Aminoiminomethyl)-N-methylglycine monohydrate', 'ND', 'ND'),
        (6537, 'Cucurbita pepo', 'ND', 'Seed(s)'),
        (6538, 'Pepsin A', 'ND', 'Pepsin A'),
        (6539, 'Tussilago farfara', 'ND', 'Flower'),
        (6540, 'Carica papaya', 'ND', 'Fruit'),
        (6541, 'Platycodon grandiflorus', 'ND', 'ND'),
        (6542, 'Agnus castus', 'ND', 'Berries'),
        (6543, 'Rosa roxburghii', 'ND', 'Whole fruit'),
        (6544, '1,3-beta-D-xylan xylanohydrolase', 'ND', 'Aspergillus niger - Whole'),
        (6545, 'Vanadium', 'ND', 'Vanadium citrate'),
        (6546, 'Citrus limon', 'ND', 'Fruit peel outer'),
        (6547, 'Riboflavin', 'ND', 'ND'),
        (6548, 'Mentha x piperita', 'ND', 'Flower'),
        (6549, 'Chromium', 'ND', 'Chromium (III) HVP chelate'),
        (6550, 'L-Arginine', 'ND', 'ND'),
        (6551, 'Bifidobacterium longum subsp. infantis', 'ND', 'Whole cell - Bifidobacterium longum subsp. Infantis R0033'),
        (6552, 'Triacylglycerol lipase', 'ND', 'Aspergillus niger - Whole'),
        (6553, 'Codonopsis pilosula', 'ND', 'Root'),
        (6554, '2-Propanol', 'ND', 'Isopropyl alcohol'),
        (6555, '1-Ethenyl-2-pyrrolidinone homopolymer compound with iodine', 'ND', 'ND'),
        (6556, 'Ethyl alcohol', 'ND', 'ND'),
        (6557, 'Casein micelles', 'ND', 'Micellar casein'),
        (6558, 'Green Coffee Bean Extract', 'ND', 'ND'),
        (6559, 'Ginkgo biloba', 'Dry', 'Leaf'),
        (6560, 'Eupatorium perfoliatum', 'ND', 'Leaf/Leaves'),
        (6561, 'L-Lysine', 'ND', 'L-Lysine monohydrochloride'),
        (6562, 'D-Pantothenic Acid', 'ND', 'Calcium D-pantothenate'),
        (6563, 'Zanthoxylum nitidum', 'Dry', 'Root'),
        (6564, 'Vitamin B12', 'ND', 'Hydroxocobalamin'),
        (6565, 'Citrus bioflavonoids', 'ND', 'Citrus limon - Fruit peel'),
        (6566, 'Melissa officinalis', 'Dry', 'Melissa officinalis - Herb top'),
        (6567, 'Buglossoides arvensis', 'ND', 'Seed(s)'),
        (6568, 'Withania somnifera', 'Dry', 'Withania somnifera - root'),
        (6569, 'Royal jelly', 'ND', 'Apis mellifera - secretion'),
        (6570, '[N-beta-Alanyl-L-histidinato(2-)-N,NN,Oalpha]zinc', 'ND', 'polaprezinc'),
        (6571, 'Paeonia lactiflora', 'ND', 'Root'),
        (6572, 'Folate', 'ND', 'Folate'),
        (6573, '2-Amino-2-deoxy-D-glucose sulfate', 'ND', 'Glucosamine Sulfate sodium Chloride'),
        (6574, 'Chromium', 'ND', 'Chromium (III) picolinate'),
        (6575, 'Pantothenic acid', 'ND', 'Calcium D-pantothenate'),
        (6576, 'Glycyrrhiza glabra', 'ND', 'Root'),
        (6577, '(alphaS)-alpha-Carboxy-2,3-dihydro-N,N,N-trimethyl-2-thioxo-1H-imidazole-4-ethanaminium inner salt', 'ND', 'Saccharomyces cerevisiae - Whole cell for biosynthesis'),
        (6578, '2-Hydroxy-N,N,N-trimethylethanaminium', 'ND', 'Choline bitartrate'),
        (6579, 'dl-Menthol', 'ND', 'ND'),
        (6580, 'L-Methionine', 'ND', 'dl-Methionine'),
        (6581, 'Rice Protein', 'ND', 'Rice Protein'),
        (6582, '3,3'',4'',5,7-Pentahydroxyflavone', 'ND', 'Quercetin dihydrate'),
        (6583, 'Trogopterus xanthipes', 'ND', 'Dung'),
        (6584, 'Iron', 'ND', 'ND'),
        (6585, 'Lactobacillus paracasei', 'ND', '13434'),
        (6586, 'Panax ginseng', 'Dry', 'Root'),
        (6587, 'Hansenia forbesii', 'Dry', 'Root and rhizome'),
        (6588, 'Vitamin A', 'ND', 'Vitamin A'),
        (6589, 'Spirulina platensis', 'ND', 'Whole cell'),
        (6590, 'Citrus paradisi', 'ND', 'Fruit peel'),
        (6591, 'Lactobacillus acidophilus', 'ND', 'Lactobacillus acidophilus - Whole cell'),
        (6592, 'Calcium phosphate hydroxide', 'ND', 'Durapatite'),
        (6593, 'Echinacea purpurea', 'ND', 'Echinacea purpurea - Root'),
        (6594, 'Niacin', 'ND', 'Niacin'),
        (6595, 'Iron', 'ND', 'Ferric glycinate'),
        (6596, 'Bacopa monnieri', 'Dry', 'Whole plant'),
        (6597, 'Bifidobacterium bifidum', 'ND', 'R-0071'),
        (6598, 'Ginkgo biloba', 'ND', 'Leaf/Leaves'),
        (6599, 'Glycyrrhiza uralensis', 'ND', 'Root'),
        (6600, 'Corydalis yanhusuo', 'ND', 'Rhizome'),
        (6601, 'Iode', 'ND', 'Potassium iodide'),
        (6602, 'Calcium', 'ND', 'Calcium carbonate'),
        (6603, 'Arsenicum album', 'ND', 'Aresenic anhydride'),
        (6604, 'Atractylodes macrocephala', 'ND', 'Rhizome (fried)'),
        (6605, 'Whey protein isolate', 'ND', 'Bos taurus - Milk'),
        (6606, 'Magnesium', 'ND', 'Magnesium citrate'),
        (6607, 'Amanita muscaria', 'ND', 'Entire fungus'),
        (6608, 'Trigonella foenum-graecum', 'Dry', 'Trigonella foenum-graecum - seed'),
        (6609, 'Alisma plantago-aquatica subsp. orientale', 'ND', 'ND'),
        (6610, 'Fritillaria unibracteata', 'Dry', 'Bulb'),
        (6611, 'Bifidobacterium bifidum', 'ND', 'HA-132'),
        (6612, 'Frangula alnus', 'ND', 'Aged bark'),
        (6613, 'Dolomiaea soulei', 'ND', 'Root'),
        (6614, 'Plantago major', 'ND', 'Leaf/Leaves'),
        (6615, 'Manganese', 'ND', 'Manganese (II) citrate'),
        (6616, '(3R,3''R)-beta,beta-Carotene-3,3''-diol', 'ND', 'Zeaxanthin'),
        (6617, '2-(Methoxycarbonyl)phenol', 'ND', 'Methyl salicylate'),
        (6618, 'Equisetum arvense', 'Dry', 'Equisetum arvense - Herb top'),
        (6619, 'Brassica oleracea var. italica', 'ND', 'Herb top'),
        (6620, 'Vitamin C', 'ND', 'Sodium ascorbate'),
        (6621, 'Vitamin K2', 'ND', 'Menaquinone 4'),
        (6622, 'Ganoderma lucidum', 'ND', 'Ganoderma lucidum - Whole'),
        (6623, '(2R)-2-(Acetyloxy)-3-carboxy-N,N,N-trimethyl-1-propanaminium inner salt', 'ND', 'Acetyl-L-Carnitine'),
        (6624, 'Magnesium', 'ND', 'Magnesium sulfate'),
        (6625, 'Taraxacum officinale', 'ND', 'Whole plant gathered before the perfection of the flowers'),
        (6626, '2-Amino-2-deoxy-D-glucose sulfate', 'ND', 'Lobster exoskeleton'),
        (6627, 'Juniperus communis', 'ND', 'Berry/Berries'),
        (6628, '3,7-Dihydro-1,3,7-trimethyl-1H-purine-2,6-dione', 'ND', 'ND'),
        (6629, 'Calcium', 'ND', 'Calcium ascorbate'),
        (6630, 'Phyllanthus emblica', 'Dry', 'Phyllanthus emblica - fruit'),
        (6631, '(2R)-2-(Acetyloxy)-3-carboxy-N,N,N-trimethyl-1-propanaminium inner salt', 'ND', 'Acetyl-L-Carnitine Hydrochloride'),
        (6632, 'Garcinia gummi-gutta', 'Dry', 'Garcinia gummi-gutta - Fruit peel'),
        (6633, 'Calcium beta-hydroxy-beta-methylbutyrate', 'ND', 'Calcium beta-hydroxy-beta-methylbutyrate'),
        (6634, 'Uva-ursi', 'ND', 'Leaves'),
        (6635, '3,3''-dihydroxy-4,4''-diketo-beta-carotene', 'ND', 'Haematococcus pluvialis - whole'),
        (6636, 'Citrus sinensis', 'ND', 'Fruit peel'),
        (6637, 'N-Acetyl-5-methoxytryptamine', 'ND', 'Melatonin'),
        (6638, 'Vaccinium myrtillus', 'ND', 'Fruit extract'),
        (6639, 'Potassium', 'ND', 'Potassium phosphate dibasic'),
        (6640, 'Phyllanthus emblica', 'ND', 'Phyllanthus emblica - fruit'),
        (6641, 'Vitamin D', 'ND', 'Vitamin D3'),
        (6642, 'Copper', 'ND', 'Copper (II) hydrolyzed vegetable protein (HVP) chelate'),
        (6643, 'Brassica oleracea var. italica', 'ND', 'Flowering top(s)'),
        (6644, 'Dendrobium chrysanthum', 'Dry', 'Stem(s)'),
        (6645, 'Pueraria lobata', 'ND', 'Root'),
        (6646, 'Haematococcus pluvialis', 'ND', 'Haematococcus pluvialis - whole'),
        (6647, 'Vitamin A', 'ND', 'Beta carotene'),
        (6648, 'Vitamin D', 'ND', 'Cladina rangiferina - Whole'),
        (6649, 'Plantago ovata', 'ND', 'Husk'),
        (6650, 'Uncaria tomentosa', 'ND', 'Stem bark'),
        (6651, 'Artemisia argyi', 'ND', 'ND'),
        (6652, 'Angelica sinensis', 'ND', 'Angelica sinensis - Root'),
        (6653, 'Cervus punjabensis', 'Dry', 'Bone - fossilised'),
        (6654, 'Persicaria hydropiper', 'ND', 'Whole plant'),
        (6655, 'Magnesium', 'ND', 'Magnesium ascorbate'),
        (6656, 'L-Lysine', 'ND', 'L-Lysine'),
        (6657, 'Prunus cerasus', 'Dry', 'Fruit'),
        (6658, 'Copper', 'ND', 'Cupric gluconate'),
        (6659, 'Copper', 'ND', 'Cupric sulfate'),
        (6660, 'Palmaria palmata', 'ND', 'Alga'),
        (6661, '3,3'',4'',5,7-pentahydroxyflavone', 'ND', 'Styphnolobium japonicum'),
        (6662, 'Fruit Blend', 'ND', 'Fragaria vesca - Fruit'),
        (6663, 'Fish oil', 'ND', 'Scombridae - Whole'),
        (6664, 'Bifidobacterium bifidum', 'ND', 'SD-6576'),
        (6665, 'Lactobacillus delbrueckii subsp. bulgaricus', 'ND', 'LB-87'),
        (6666, 'Lacticaseibacillus rhamnosus', 'ND', 'Whole cell'),
        (6667, 'Vaccinium myrtillus', 'ND', 'Fruit (standardized extract)'),
        (6668, 'Lycopodium clavatum', 'ND', 'Spores'),
        (6669, 'Vitamin E', 'ND', 'd-alpha Tocopheryl acid succinate'),
        (6670, '(alphaS)-alpha-[(1S)-1-(Methylamino)ethyl]benzenemethanol', 'ND', 'Pseudoephedrine hydrochloride'),
        (6671, 'Boswellia serrata', 'ND', 'Gum oleoresin'),
        (6672, 'Magnesium', 'ND', 'Magnesium oxide'),
        (6673, 'Tribulus terrestris', 'ND', 'Fruit'),
        (6674, 'DL-alpha-Lipoic acid', 'ND', 'DL-alpha-Lipoic acid'),
        (6675, 'Zingiber officinale', 'ND', 'Root'),
        (6676, 'Withania somnifera', 'Dry', 'Leaf'),
        (6677, 'Citrus sinensis', 'ND', 'Citrus sinensis - fruit'),
        (6678, '1,4-Benzenediol', 'ND', 'Hydroquinone'),
        (6679, 'Wolfiporia extensa', 'Dry', 'ND'),
        (6680, 'Garcinia gummi-gutta', 'ND', 'Garcinia gummi-gutta - Fruit peel'),
        (6681, 'Zinc', 'ND', 'Zinc amino acid chelate'),
        (6682, 'Glycyrrhiza glabra', 'ND', 'ND'),
        (6683, 'Soy protein isolate', 'ND', 'Glycine spp.'),
        (6684, 'Tribulus terrestris', 'decoction', 'Root'),
        (6685, 'Ginkgo biloba', 'Dry', 'Seed(s)'),
        (6686, 'Magnesium', 'ND', 'Magnesium aspartate'),
        (6687, 'Lachesis mutus', 'ND', 'Venom'),
        (6688, 'Citrus limon', 'ND', 'Fruit'),
        (6689, 'L-Arginine', 'ND', 'L-Arginine alpha-ketoglutarate'),
        (6690, 'Vitamin A', 'ND', 'ND'),
        (6691, 'Camellia sinensis', 'ND', 'Leaf'),
        (6692, 'Curcuma longa', 'ND', 'Root'),
        (6693, '1,4-alpha-D-Glucan glucohydrolase', 'ND', 'Aspergillus niger - Whole'),
        (6694, '3,3'',4'',5,7-Pentahydroxyflavone', 'ND', 'Styphnolobium japonicum - whole'),
        (6695, 'Vitamin C', 'ND', 'Calcium ascorbate'),
        (6696, 'Stem bromelain', 'ND', 'Ananas comosus var. comosus - Stem'),
        (6697, 'L-Tyrosine', 'ND', 'L-Tyrosine'),
        (6698, 'Calcium', 'ND', 'Calcium phosphate, monobasic, monohydrate'),
        (6699, 'Vitamin D', 'ND', 'Ergocalciferol'),
        (6700, 'Calendula officinalis', 'ND', 'Flower'),
        (6701, 'Areca catechu', 'Dry', 'Fruit pericarp'),
        (6702, 'Cinnamomum aromaticum', 'ND', 'Twig(s)'),
        (6703, '2-(3,4-Dihydroxyphenyl)ethanol', 'ND', 'Olea europaea - leaf'),
        (6704, 'Tremella fuciformis', 'ND', 'ND'),
        (6705, 'Perilla frutescens', 'ND', 'Leaf'),
        (6706, '1-Carboxy-N,N,N-trimethylmethanaminium inner salt', 'ND', 'Betaine'),
        (6707, 'Pogostemon cablin', 'ND', 'Leaf'),
        (6708, 'L-Carnitine', 'ND', 'L-Carnitine tartrate'),
        (6709, 'Curcuma longa', 'ND', 'Rhizome'),
        (6710, 'Cyathula officinalis', 'ND', 'ND'),
        (6711, 'Dioscorea oppositifolia', 'ND', 'ND'),
        (6712, 'Juglans regia', 'ND', 'Leaves and rind of the green, unripe fruit, in equal parts'),
        (6713, 'Sus scrofa', 'ND', 'Mucous membrane of the gums'),
        (6714, 'Pantothenic acid', 'ND', 'DL-Pantothenic acid'),
        (6715, '1H-Pyrrolo(2,3-f)quinoline-2,7,9-tricarboxylic acid, 4,5-dihydro-4,5-dioxo-', 'ND', 'Pyrroloquinoline quinone disodium salt'),
        (6716, 'Lacticaseibacillus rhamnosus', 'ND', 'GG'),
        (6717, 'Bifidobacterium longum subsp. longum', 'ND', 'Whole cell - Bifidobacterium longum subsp. Longum HA-135'),
        (6718, 'Lactobacillus helveticus', 'ND', 'R-0052'),
        (6719, 'Folate', 'ND', 'Calcium L-5-methyltetrahydrofolate'),
        (6720, 'Arnica montana', 'ND', 'Flower'),
        (6721, 'Manganese', 'ND', 'Manganese amino acid chelate'),
        (6722, 'Zinc', 'ND', 'Zinc hydrolyzed vegetable protein (HVP) chelate'),
        (6723, 'Silybum marianum', 'ND', 'Seed extract'),
        (6724, 'Pediococcus acidilactici', 'ND', 'Whole cell'),
        (6725, 'Camellia sinensis', 'ND', 'Leaf extract'),
        (6726, 'Althaea officinalis', 'ND', 'Root'),
        (6727, 'Vitex agnus-castus', 'Dry', 'Vitex agnus-castus - Fruit'),
        (6728, 'Papain', 'ND', 'Carica papaya'),
        (6729, 'Pinus massoniana', 'ND', 'ND'),
        (6730, 'Triticum aestivum', 'ND', 'Grain'),
        (6731, 'Lycopene', 'ND', 'Solanum lycopersicum - Fruit flesh'),
        (6732, 'L-Serine', 'ND', 'L-Serine'),
        (6733, 'Rehmannia glutinosa', 'ND', 'ND'),
        (6734, 'Condurango', 'ND', 'Bark'),
        (6735, 'Zinc', 'ND', 'Zinc picolinate'),
        (6736, 'Lytta vesicatoria', 'ND', 'Fly(Flies)'),
        (6737, 'Iron', 'ND', 'Iron (II) fumarate'),
        (6738, 'Apis mellifica', 'ND', 'Bee'),
        (6739, 'Ligusticum sinense cv. chuanxiong', 'Dry', 'Rhizome'),
        (6740, '(3R,3''R,6''R)-beta,epsilon-Carotene-3,3''-diol', 'ND', 'Lutein (USP)'),
        (6741, 'Bacillus coagulans', 'ND', 'MTCC 5856'),
        (6742, 'L-Ascorbic acid', 'ND', 'Ascorbic acid'),
        (6743, '(1-4)-alpha-D-galacturonan glycanohydrolase', 'ND', 'Aspergillus niger - Whole'),
        (6744, 'Pectin', 'ND', 'Citrus paradisi - Fruit'),
        (6745, 'Lactobacillus casei', 'ND', 'Whole cell - Lactobacillus casei HA-108'),
        (6746, 'All-trans-lycopene', 'ND', 'Lycopene'),
        (6747, 'Lactobacillus rhamnosus', 'ND', 'Whole cell'),
        (6748, 'Vitamin B6', 'ND', 'ND'),
        (6749, 'Paeonia lactiflora', 'Dry', 'ND'),
        (6750, 'Camellia sinensis', 'ND', 'Camellia sinensis - leaf'),
        (6751, 'Vaccinium angustifolium', 'ND', 'Fruit'),
        (6752, 'Vitamin E', 'ND', 'D-alpha tocopheryl acetate'),
        (6753, 'D-Mannose', 'ND', 'D-Mannose'),
        (6754, 'L-Cysteine', 'ND', 'L-Cysteine'),
        (6755, 'Perilla frutescens', 'ND', 'ND'),
        (6756, 'Calcium', 'ND', 'Coral - calcareous skeleton'),
        (6757, 'Green Coffee Bean Extract', 'Dry', 'ND'),
        (6758, 'Manganese', 'ND', 'Manganese (II) sulfate'),
        (6759, 'Eupatorium perfoliatum', 'ND', 'Root'),
        (6760, 'Lactobacillus casei', 'ND', 'HA-108'),
        (6761, 'Ethyl alcohol', 'ND', 'Ethanol'),
        (6762, 'Rehmannia glutinosa', 'Dry', 'ND'),
        (6763, 'Magnesium', 'ND', 'ND'),
        (6764, 'Prunus avium', 'ND', 'Prunus avium - fruit'),
        (6765, 'Trametes versicolor', 'Dry', 'Fruiting body'),
        (6766, 'Cyperus rotundus', 'ND', 'Root'),
        (6767, 'Prunus africana', 'ND', 'Stem bark'),
        (6768, 'Cinnamomum verum', 'ND', 'Bark'),
        (6769, 'Serenoa repens', 'ND', 'ND'),
        (6770, 'Methylsulfonylmethane', 'ND', 'Dimethyl sulfone'),
        (6771, 'Codonopsis pilosula', 'ND', 'Codonopsis pilosula - Root'),
        (6772, 'Pantothenic acid', 'ND', 'Dexpanthenol'),
        (6773, 'Daemonorops draco', 'Dry', 'Fruit Resin'),
        (6774, 'Rhodiola rosea', 'Dry', 'Root'),
        (6775, 'Vitamin A', 'ND', 'Vitamin A acetate'),
        (6776, 'Ophiocordyceps sinensis', 'Dry', 'Mycelia'),
        (6777, 'Beta-carotene', 'ND', 'ND'),
        (6778, 'Olea europaea', 'ND', 'Leaf'),
        (6779, 'Alpinia officinarum', 'Dry', 'Rhizome'),
        (6780, 'Citrus aurantium', 'ND', 'Citrus aurantium - fruit'),
        (6781, 'Lacticaseibacillus paracasei', 'ND', 'LPC-37'),
        (6782, 'Beta-fructofuranosidase', 'ND', 'Saccharomyces spp.'),
        (6783, 'Taraxacum officinale', 'ND', 'Leaf'),
        (6784, 'Fruit Blend', 'ND', 'Vaccinium corymbosum - Fruit'),
        (6785, 'Aucklandia lappa', 'ND', 'Root'),
        (6786, '(3R,3''R)-beta,beta-Carotene-3,3''-diol', 'ND', 'Tagetes erecta - Herb flowering oleoresin'),
        (6787, 'Phellodendron chinense', 'Dry', 'Stem bark'),
        (6788, 'Prunus armeniaca', 'ND', 'Seed(s)'),
        (6789, 'Clematis armandii', 'Dry', 'Stem(s)'),
        (6790, 'Hydrargyrum sulfuratum rubrum', 'ND', 'Hydrargyrum (mercury)'),
        (6791, 'Salvia miltiorrhiza', 'ND', 'Root'),
        (6792, 'Betaine hydrochloride', 'ND', 'Betaine hydrochloride'),
        (6793, 'Punica granatum', 'Dry', 'Fruit'),
        (6794, 'Thiamine', 'ND', 'Thiamine'),
        (6795, 'Crassostrea gigas', 'Dry', 'Shell'),
        (6796, 'Lactobacillus rhamnosus', 'ND', 'Lactobacillus rhamnosus - Whole cell'),
        (6797, 'Copper', 'ND', 'Copper (II) sulfate'),
        (6798, 'Fish oil', 'ND', 'Clupeidae - Whole'),
        (6799, 'Hops polyphenols - Rice protein complex', 'ND', 'Hops polyphenols - Rice protein complex'),
        (6800, 'Rice protein concentrate', 'ND', 'Oryza sativa - Seed'),
        (6801, 'Melaleuca quinquenervia', 'ND', 'Leaves and twigs'),
        (6802, 'Bupleurum chinense', 'ND', 'ND'),
        (6803, 'Vitamin B12', 'ND', 'Cyanocobalamin'),
        (6804, 'Boswellia serrata', 'Dry', 'ND'),
        (6805, 'Niacinamide', 'ND', 'Niacinamide'),
        (6806, 'Ziziphus jujuba', 'Dry', 'Ziziphus jujuba - Fruit'),
        (6807, 'Bacillus subtilis subsp. inaquosorum', 'ND', 'Whole cell'),
        (6808, 'para-Aminobenzoic acid', 'ND', 'Saccharomyces cerevisiae - whole'),
        (6809, 'Lactobacillus salivarius', 'ND', 'Whole cell - Lactobacillus salivarius HA-118'),
        (6810, 'Brassica oleracea var. italica', 'ND', 'Brassica oleracea var. italica - herb top'),
        (6811, 'Echinacea purpurea', 'ND', 'ND'),
        (6812, 'Rumex crispus', 'ND', 'Root'),
        (6813, 'Paeonia suffruticosa', 'ND', 'ND'),
        (6814, 'Sambucus nigra subsp. canadensis', 'Fresh', 'Fruit'),
        (6815, 'Rosa laevigata', 'ND', 'Fruit'),
        (6816, 'Krill oil', 'ND', 'Euphausia superba - Whole'),
        (6817, 'Solanum lycopersicum', 'Dry', 'Fruit flesh'),
        (6818, 'Bifidobacterium animalis subsp. lactis', 'ND', 'BL-04'),
        (6819, 'Lactobacillus acidophilus', 'ND', 'Lactobacillus acidophilus Rosell-11 - Whole cell'),
        (6820, 'Black horehound', 'ND', 'ND'),
        (6821, 'Gentiana lutea', 'ND', 'Root'),
        (6822, 'Schizochytrium spp.', 'ND', 'Whole'),
        (6823, 'Bifidobacterium breve', 'ND', 'HA-129'),
        (6824, 'Seal oil', 'ND', 'ND'),
        (6825, 'Zinc', 'ND', 'Zinc sulfate'),
        (6826, 'Lactobacillus rhamnosus', 'ND', 'Whole cell - Lactobacillus rhamnosus HA-114'),
        (6827, 'All-trans-beta-carotene', 'ND', 'ND'),
        (6828, 'L-Alanine', 'ND', 'L-Alanine'),
        (6829, 'All-trans-lycopene', 'ND', 'Fruit flesh'),
        (6830, 'Vitamin C', 'ND', 'Ascorbic acid'),
        (6831, 'Syzygium jambolanum', 'ND', 'Crushed seed'),
        (6832, 'Lactobacillus casei', 'ND', 'Whole cell'),
        (6833, 'Bacillus subtilis subsp. inaquosorum', 'ND', 'DE111'),
        (6834, 'Grape seed extract', 'Dry', 'Vitis vinifera - Seed'),
        (6835, 'Lactococcus lactis', 'ND', 'Whole cell'),
        (6836, 'Partially hydrolysed chicken eggshell membrane', 'ND', 'Gallus gallus - Egg shell'),
        (6837, 'Linum usitatissimum', 'ND', 'Seed(s)'),
        (6838, 'Sabal serrulata', 'ND', 'Ripe fruit(s)'),
        (6839, 'Citrus paradisi', 'ND', 'Fruit'),
        (6840, 'Pectin pectylhydrolase', 'ND', 'Aspergillus niger - Whole'),
        (6841, 'Matricaria chamomilla', 'Dry', 'ND'),
        (6842, 'Okoubaka aubrevillei', 'ND', 'Bark'),
        (6843, 'Carthamus tinctorius', 'ND', 'Carthamus tinctorius - Flower'),
        (6844, 'Propolis', 'ND', 'Apis mellifera - beehive'),
        (6845, 'Panax notoginseng', 'ND', 'Root'),
        (6846, 'Potassium', 'ND', 'Potassium chloride'),
        (6847, 'Citrus aurantium', 'ND', 'Flower'),
        (6848, '(all-E)-2,6,10,15,19,23-Hexamethyl-2,6,10,14,18,22-tetracosahexaene', 'ND', 'Olea europaea - Fruit'),
        (6849, 'Allium sativum', 'Dry', 'Allium sativum - Bulb'),
        (6850, 'Taraxacum officinale', 'ND', 'Root glycerine extract'),
        (6851, 'Trametes versicolor', 'ND', 'Trametes versicolor - Fruiting body'),
        (6852, 'Glycyrrhiza uralensis', 'Dry', 'Root'),
        (6853, 'L-Arginine', 'ND', 'L-Arginine monohydrochloride'),
        (6854, 'Piper nigrum', 'ND', 'Fruit'),
        (6855, 'Lachesis mutus', 'ND', 'Lactose'),
        (6856, 'Ribo-2,3,4,5-tetrahydroxyvaleraldehyde, D-', 'ND', 'Ribose'),
        (6857, 'Boron', 'ND', 'Sodium borate'),
        (6858, 'Ligilactobacillus salivarius', 'ND', 'Ls-33'),
        (6859, 'Citrus bergamia', 'ND', 'Fruit'),
        (6860, 'Malpighia glabra', 'ND', 'Fruit'),
        (6861, 'Alpinia oxyphylla', 'ND', 'Fruit'),
        (6862, '2-Amino-2-deoxy-D-glucose sulfate', 'ND', 'Shrimp exoskeleton'),
        (6863, 'Pinellia ternata', 'Dry', 'Rhizome'),
        (6864, 'Thymus vulgaris', 'Extract Type TBA', 'Flower'),
        (6865, 'Cinchona officinalis', 'ND', 'Bark'),
        (6866, 'Solanum lycopersicum', 'ND', 'Fruit'),
        (6867, 'Butanoic acid', 'ND', 'Butyric acid'),
        (6868, 'Prunus africana', 'ND', 'Bark'),
        (6869, 'Houttuynia cordata', 'ND', 'ND'),
        (6870, 'Sparganium eurycarpum', 'ND', 'ND'),
        (6871, 'Zinc', 'ND', 'Zinc oxide'),
        (6872, 'Glycosaminoglycans', 'ND', 'Bos taurus - cartilage'),
        (6873, '(2S)-7-[[6-O-(6-Deoxy-alpha-L-mannopyranosyl)-beta-D-glucopyranosyl]oxy]-2,3-dihydro-5-hydroxy-2-(3-hydroxy-4-methoxyphenyl)-4H-1-benzopyran-4-one', 'ND', 'Hesperidin'),
        (6874, '3-Pyridinecarboxamide', 'ND', 'Niacinamide'),
        (6875, 'Magnesia phosphorica', 'ND', 'Magnesium phosphaten dibasic'),
        (6876, 'Levocarnitine', 'ND', 'L-Carnitine tartrate'),
        (6877, 'Vitamin C', 'ND', 'Magnesium ascorbate'),
        (6878, 'Uncaria rhynchophylla', 'decoction', 'Twigs'),
        (6879, 'Bos taurus', 'ND', 'Adrenal gland'),
        (6880, 'Hericium erinaceus', 'Dry', 'Stroma'),
        (6881, 'Zingiber officinale', 'ND', 'Rhizome'),
        (6882, 'Mentha x piperita', 'ND', 'Leaf'),
        (6883, '3-[[6-0-(6-deoxy-alpha-L-mannopyranosyl)-beta-D-glucopyranosyl] oxy-2(3,4-dihydroxyphenyl)-5, 7-dihydroxy-4H-1-benzopyran-4-one', 'ND', 'Styphnolobium japonicum'),
        (6884, 'Nasturtium officinale', 'Dry', 'Herb top'),
        (6885, 'Vitex rotundifolia', 'decoction', 'Fruit'),
        (6886, 'Solidago virgaurea', 'ND', 'Flower buds'),
        (6887, 'Atropa belladonna', 'ND', 'Whole plant(s)'),
        (6888, 'Bifidobacterium longum subsp. longum', 'ND', 'BL-05'),
        (6889, 'Hedeoma pulegioides', 'ND', 'ND'),
        (6890, 'Vaccinium macrocarpon', 'ND', 'Fruit'),
        (6891, 'Calcium', 'ND', 'Bos taurus - Milk'),
        (6892, 'Inonotus obliquus', 'ND', 'Inonotus obliquus - Fruiting body'),
        (6893, 'Poly(1-4-a-D-galacturonide)glycanohydrolase', 'ND', 'Aspergillus niger - Whole'),
        (6894, 'Bifidobacterium animalis subsp. animalis', 'ND', 'Whole cell'),
        (6895, 'Thymus vulgaris', 'ND', 'Leaf'),
        (6896, 'Bifidobacterium bifidum', 'ND', 'BB-06'),
        (6897, 'Phaseolus vulgaris', 'ND', 'Seed(s)'),
        (6898, 'Glucosamine hydrochloride', 'ND', 'Shellfish exoskeleton'),
        (6899, 'Epimedium sagittatum', 'ND', 'Leaf'),
        (6900, 'Eleutherococcus senticosus', 'ND', 'Root extract'),
        (6901, 'Beta-carotene', 'ND', 'Beta carotene'),
        (6902, 'Boron', 'ND', 'Boron citrate'),
        (6903, 'Tanacetum parthenium', 'ND', 'Aerial parts'),
        (6904, 'Casein', 'ND', 'Sodium Caseinate from bovine milk'),
        (6905, '1-Amino-4-guanidinobutane', 'ND', 'Agmatine sulfate'),
        (6906, 'Angelica pubescens', 'Dry', 'Root'),
        (6907, 'Echinacea angustifolia', 'ND', 'Root'),
        (6908, 'Vitamin C', 'ND', 'ND'),
        (6909, 'Calcium', 'ND', 'Calcium lactate'),
        (6910, 'Selenium', 'ND', 'Selenium-enriched yeast'),
        (6911, 'Pea Protein', 'ND', 'Pisum sativum - seed'),
        (6912, 'Ginkgo biloba', 'ND', 'Leaf'),
        (6913, 'L-Tyrosine', 'ND', 'Anas falcata - feather'),
        (6914, 'Vaccinium vitis-idaea', 'ND', 'Vaccinium vitis-idaea'),
        (6915, 'Eleutherococcus senticosus', 'Dry', 'Root'),
        (6916, '2-amino-2-deoxy-D-glucose sulfate', 'ND', 'Glucosamine sulfate'),
        (6917, 'Ophiopogon japonicus', 'Dry', 'Tuber'),
        (6918, 'Senna alexandrina', 'Dry', 'Leaf'),
        (6919, 'Triacylglycerol lipase', 'ND', 'Aspergillus flavus var. oryzae - Whole'),
        (6920, 'Curcuma kwangsiensis', 'ND', 'ND'),
        (6921, '(alphaS)-alpha-[(1S)-1-(Methylamino)ethyl]benzenemethanol', 'ND', 'Pseudoephedrine sulfate'),
        (6922, 'Vitamin B12', 'ND', 'ND'),
        (6923, 'Urtica dioica', 'Dry', 'Urtica dioica - herb top'),
        (6924, 'Magnesium', 'ND', 'Magnesium chloride'),
        (6925, 'Mucuna pruriens', 'ND', 'Seed(s)'),
        (6926, 'Allium sativum', 'ND', 'Bulb'),
        (6927, 'Protease', 'ND', 'Aspergillus niger - Whole'),
        (6928, 'Saposhnikovia divaricata', 'Dry', 'Root'),
        (6929, 'Bifidobacterium animalis subsp. Lactis', 'ND', 'R-0421'),
        (6930, 'Lentinula edodes', 'ND', 'Lentinula edodes - fruiting body'),
        (6931, 'Vanadium', 'ND', 'Vanadyl sulfate'),
        (6932, 'Carbonic acid calcium salt (1:1)', 'ND', 'Gallus Gallus (chicken) shell'),
        (6933, 'Pantothenic acid', 'ND', 'd-Pantothenic acid'),
        (6934, 'Chromium', 'ND', 'Chromium (III) hydrolyzed vegetable protein (HVP) chelate'),
        (6935, 'Triticum aestivum', 'ND', 'Seed(s)'),
        (6936, 'Descurainia sophia', 'Dry', 'Seed(s)'),
        (6937, 'Vitamin B6', 'ND', 'Pyridoxal 5-phosphate'),
        (6938, 'Psidium guajava', 'ND', 'Fruit'),
        (6939, 'N-acetyl-5-methoxytryptamine', 'ND', 'Non-human animals non-susceptible to TSE - Pineal gland'),
        (6940, 'Angelica sinensis', 'Dry', 'Angelica sinensis - Root'),
        (6941, 'Vitamin C', 'ND', 'Vitamin C'),
        (6942, 'Fruit Blend', 'ND', 'Punica granatum, Fruit'),
        (6943, 'Niacin', 'ND', 'Niacinamide'),
        (6944, '4-(1,3;1,4)-beta-D-Glucan 4-glucanohydrolase', 'ND', 'Trichoderma reesei - whole'),
        (6945, 'Glycyrrhiza uralensis', 'decoction', 'Root'),
        (6946, '2-Amino-2-deoxy-beta-D-glucopyranose hydrochloride', 'ND', 'Exoskeleton of shrimp, crab and lobster'),
        (6947, 'Vitamin E', 'ND', 'DL-alpha tocopheryl acetate'),
        (6948, '2-Aminoethanesulfonic acid', 'ND', 'Taurine'),
        (6949, 'Selenium', 'ND', 'Selenium yeast'),
        (6950, 'L-Theanine', 'ND', 'L-Theanine'),
        (6951, 'L-Valine', 'ND', 'L-valine'),
        (6952, '4''-Hydroxy-3,5-dimethoxystilbene', 'ND', 'Pterocarpus marsupium - stem heartwood'),
        (6953, 'Chromium', 'ND', 'Chromium (III) polynicotinate'),
        (6954, 'Ophiopogon japonicus', 'ND', 'ND'),
        (6955, 'Iodine', 'ND', 'Fucus vesiculosus - Whole plant'),
        (6956, 'Trigonella foenum-graecum', 'ND', 'Seed(s)'),
        (6957, 'Olea europaea', 'ND', 'Olea europaea - leaf'),
        (6958, 'Lilium lancifolium', 'Dry', 'Lilium lancifolium - Bulb'),
        (6959, 'Vitamin E', 'ND', 'd-alpha tocopherol acetate'),
        (6960, 'Crataegus cuneata', 'ND', 'Fruit'),
        (6961, 'Boswellia serrata', 'Dry', 'Trunk bark oleogum resin'),
        (6962, '(beta-Hydroxyethyl)trimethylammonium', 'ND', 'ND'),
        (6963, 'D-Camphor', 'ND', 'd-Camphor'),
        (6964, 'Boricum acidum', 'ND', 'Boracic acid'),
        (6965, 'Carbonic acid calcium salt (1:1)', 'ND', 'Calcium carbonate'),
        (6966, 'Phytolacca decandra', 'ND', 'Root'),
        (6967, 'L-Arginine', 'ND', 'L-arginine'),
        (6968, 'Triacylglycerol acylhydrolase', 'ND', 'Rhizopus oryzae - Whole'),
        (6969, 'Paullinia cupana', 'ND', 'Seed(s)'),
        (6970, 'Valeriana officinalis', 'ND', 'Root'),
        (6971, 'Atractylodes macrocephala', 'Dry', 'ND'),
        (6972, 'Malva sylvestris', 'ND', 'Leaf/Leaves'),
        (6973, 'Astragalus membranaceus', 'ND', 'Root'),
        (6974, 'Lindera aggregata', 'ND', 'Root'),
        (6975, 'Lecithin', 'ND', 'Lecithin'),
        (6976, 'Glutamic Acid', 'ND', 'Glutamic acid hydrochloride'),
        (6977, 'Solanum lycopersicum', 'Dry', 'Solanum lycopersicum - Fruit flesh'),
        (6978, 'Taxillus chinensis', 'decoction', 'Herb top'),
        (6979, 'Gaultheria procumbens', 'Dry', 'Leaf'),
        (6980, 'Acidum benzoicum e resina', 'ND', 'Benzoic acid'),
        (6981, 'Collinsonia canadensis', 'ND', 'Root'),
        (6982, 'Ziziphus jujuba', 'ND', 'Fruit'),
        (6983, '2,5-Cyclohexadiene-1,4-dione, 2-[(2E,6E,10E,14E,18E,22E,26E,30E,34E)-3,7,11,15,19,23,27,31,35,39-decamethyl-2,6,10,14,18,22,26,30,34,38-tetracontadecaenyl]-5,6-dimethoxy-3-methyl', 'ND', 'Coenzyme Q10'),
        (6984, 'Trans-Resveratrol', 'ND', 'Resveratrol'),
        (6985, 'Vitamin K1', 'ND', 'ND'),
        (6986, 'Hydrolyzed collagen', 'ND', 'ND'),
        (6987, 'Amomum longiligulare', 'Dry', 'ND'),
        (6988, 'Cynara cardunculus', 'ND', 'Cynara cardunculus - Leaf'),
        (6989, 'Grifola frondosa', 'ND', 'Grifola frondosa - Fruiting body'),
        (6990, 'Zingiber officinale', 'ND', 'Zingiber officinale - Rhizome'),
        (6991, 'Bifidobacterium animalis subsp. animalis', 'ND', 'BI-04'),
        (6992, '(all-E)-2,6,10,15,19,23-Hexamethyl-2,6,10,14,18,22-tetracosahexaene', 'ND', 'Elaeis guineensis - Fruit'),
        (6993, 'Angelica dahurica', 'ND', 'New material'),
        (6994, 'L-Lysine', 'ND', 'Glycine max - Seed'),
        (6995, 'Lonicera japonica', 'Dry', 'Stem'),
        (6996, 'Sodium chloride', 'ND', 'Sodium chloride'),
        (6997, 'Helianthus annuus', 'ND', 'Seed(s)'),
        (6998, 'Zinc', 'ND', 'Zinc citrate'),
        (6999, 'Artemisia annua', 'ND', 'Whole plant'),
        (7000, 'Lyssin/Hydrophobinum', 'ND', 'Saliva of rabid dog'),
        (7001, 'Ocimum tenuiflorum', 'ND', 'Ocimum tenuiflorum - leaf'),
        (7002, '4-Aminobutanoic acid', 'ND', 'gamma-Aminobutyric acid'),
        (7003, 'Lactobacillus helveticus', 'ND', 'Lactobacillus helveticus - Whole Cell'),
        (7004, 'Krill oil', 'ND', 'Euphausia pacifica - whole'),
        (7005, 'Bacillus coagulans', 'ND', 'Whole cell'),
        (7006, 'Vitamin E', 'ND', 'dl-alpha Tocopheryl acetate'),
        (7007, 'Calcium', 'ND', 'Calcium'),
        (7008, 'Malva verticillata', 'ND', 'Leaf'),
        (7009, 'Angelica sinensis', 'Dry', 'Root'),
        (7010, 'Vitis vinifera', 'ND', 'Seed(s)'),
        (7011, 'Rubus idaeus', 'ND', 'Seed(s)'),
        (7012, 'Epimedium sagittatum', 'Dry', 'Herb top'),
        (7013, 'Magnesia phosphorica', 'ND', 'Magnesium hydrogen phosphate trihydrate'),
        (7014, 'Rosa x damascena', 'ND', 'Flower'),
        (7015, 'Arctostaphylos uva-ursi', 'ND', 'Arctostaphylos uva-ursi - Leaf'),
        (7016, 'Nepeta tenuifolia', 'Dry', 'Herb top'),
        (7017, 'Vaccinium corymbosum', 'Fresh', 'Vaccinium corymbosum - Fruit'),
        (7018, 'Copper', 'ND', 'Copper (II) gluconate'),
        (7019, 'Propolis', 'Dry', 'Apis mellifera - secretion'),
        (7020, 'Crataegus laevigata', 'ND', 'Leaf and flower'),
        (7021, 'Selenium', 'ND', 'Selenomethionine'),
        (7022, 'Inulin', 'ND', 'Cichorium intybus - Root'),
        (7023, 'Wolfiporia extensa', 'ND', 'Sclerotium'),
        (7024, 'Senna alexandrina', 'ND', 'Leaf'),
        (7025, 'Camellia sinensis extract', 'ND', 'Leaf'),
        (7026, 'Fruit Blend', 'ND', 'Vitis vinifera - Fruit'),
        (7027, 'Asparagus racemosus', 'ND', 'ND'),
        (7028, 'Rubus idaeus', 'ND', 'Leaf'),
        (7029, 'dl-Phenylalanine', 'ND', 'DL-Phenylalanine'),
        (7030, 'Copper', 'ND', 'Copper (II) carbonate'),
        (7031, 'Vitamin C', 'ND', 'Ascorbyl palmitate'),
        (7032, 'Eschscholzia californica', 'ND', 'Herb top'),
        (7033, 'Asarum sieboldii', 'Dry', 'Root and rhizome'),
        (7034, 'Salicylic acid', 'ND', 'ND'),
        (7035, 'Oenothera biennis', 'ND', 'Seed(s)'),
        (7036, 'Atractylodes macrocephala', 'Dry', 'Rhizome'),
        (7037, 'Zingiber officinale', 'ND', 'Fresh rhizome'),
        (7038, 'Actaea dahurica', 'Dry', 'Rhizome'),
        (7039, 'Kali muriaticum', 'ND', 'Kali muriaticum'),
        (7040, 'Ligusticum jeholense', 'Dry', 'Root and rhizome'),
        (7041, 'Lactococcus lactis', 'ND', 'MJC 18'),
        (7042, 'Bifidobacterium animalis subsp. lactis', 'ND', 'Whole cell'),
        (7043, 'Harpagophytum procumbens', 'Dry', 'ND'),
        (7044, 'Vaccinium macrocarpon', 'Fresh', 'Vaccinium macrocarpon- Fruit'),
        (7045, 'Chromium', 'ND', 'Chromium (III) chloride'),
        (7046, 'Papain', 'ND', 'Carica papaya, fruit'),
        (7047, 'Pectin', 'ND', 'Pectin'),
        (7048, 'Humulus lupulus', 'ND', 'Strobiles'),
        (7049, 'Pea protein', 'ND', 'Pea Proteins'),
        (7050, 'Harpagophytum procumbens', 'Dry', 'Secondary root tuber(s)'),
        (7051, 'Turnera diffusa', 'ND', 'Leaf'),
        (7052, 'L-Leucine', 'ND', 'L-Leucine'),
        (7053, 'Frangula purshiana', 'ND', 'Aged bark'),
        (7054, 'Secale cereale', 'Dry', 'ND'),
        (7055, '(Carboxymethyl)trimethylammonium hydroxide inner salt', 'ND', 'Betaine'),
        (7056, 'Boswellia serrata', 'Dry', 'Stem bark oleogum resin'),
        (7057, 'Iron', 'ND', 'Ferrous fumarate'),
        (7058, 'Vitamin E', 'ND', 'd-alpha Tocopherol'),
        (7059, 'Malpighia glabra', 'Dry', 'Fruit'),
        (7060, 'Melaleuca alternifolia', 'ND', 'Twig leafy'),
        (7061, 'Sodium fluoride', 'ND', 'ND'),
        (7062, 'Fruit Blend', 'ND', 'rubus idaeus - fruit'),
        (7063, 'Fruit Blend', 'ND', 'Vaccinium macrocarpon - Fruit powder'),
        (7064, 'Paeonia lactiflora', 'Dry', 'Root'),
        (7065, 'Glycyrrhiza uralensis', 'ND', 'ND'),
        (7066, 'Biotin', 'ND', 'Biotin'),
        (7067, 'Thiamine', 'ND', 'Thiamine mononitrate'),
        (7068, 'Tussilago farfara', 'ND', 'Leaf/Leaves'),
        (7069, 'Whey protein concentrate', 'ND', 'Whey protein concentrate'),
        (7070, 'Hydrastis canadensis', 'ND', 'ND'),
        (7071, 'L-Glutamine', 'ND', 'L-Glutamine (USP)'),
        (7072, 'Ganoderma lucidum', 'ND', 'ND'),
        (7073, 'Lactobacillus reuteri', 'ND', 'Whole cell - Lactobacillus reuteri HA-188'),
        (7074, '1-Carboxy-N,N,N-trimethylmethanaminium chloride', 'ND', 'Betaine hydrochloride'),
        (7075, 'Zinc oxide', 'ND', 'Zinc oxide'),
        (7076, 'Vitamin E', 'ND', 'd-alpha-tocopherol'),
        (7077, '(S)-2,5-Diaminopentanoic acid', 'ND', 'Ornithine Hydrochloride'),
        (7078, 'Rosa canina', 'ND', 'Flower'),
        (7079, 'Acacia', 'ND', 'Acacia group - Gum'),
        (7080, 'Serenoa repens', 'ND', 'Fruit'),
        (7081, 'Bifidobacterium animalis subsp. lactis', 'ND', 'SD-5219'),
        (7082, 'Withania somnifera', 'ND', 'Root'),
        (7083, 'Folate', 'ND', 'ND'),
        (7084, 'D-Pantothenic acid', 'ND', 'Calcium D-pantothenate'),
        (7085, 'Glucosamine sulfate', 'ND', 'Crustacean Exoskeleton'),
        (7086, 'Lactobacillus paracasei', 'ND', 'R-0422'),
        (7087, 'Medicago sativa', 'ND', 'Herb top'),
        (7088, 'Chromium', 'ND', 'Chromium amino acid chelate'),
        (7089, 'Anemone chinensis', 'ND', 'Root'),
        (7090, 'Hibiscus sabdariffa', 'Dry', 'ND'),
        (7091, 'Citrus sinensis', 'ND', 'Fruit'),
        (7092, 'Calcium caseinate', 'ND', 'Calcium caseinate'),
        (7093, 'Angelica dahurica', 'Dry', 'ND'),
        (7094, '4-(1,3;1,4)-beta-D-Glucan 4-glucanohydrolase', 'ND', 'Aspergillus niger - Whole'),
        (7095, 'Vitamin K2', 'ND', 'Menaquinone 7'),
        (7096, 'Paeonia lactiflora', 'ND', 'ND'),
        (7097, 'Carbamide', 'ND', 'Urea'),
        (7098, 'Kaolin', 'ND', 'Kaolin'),
        (7099, 'Aristotelia chilensis', 'ND', 'Fruit'),
        (7100, 'Aesculus hippocastanum', 'Dry', 'Seed(s)'),
        (7101, 'Crataegus monogyna', 'Dry', 'ND'),
        (7102, 'Lactobacillus acidophilus', 'ND', 'SD-5212'),
        (7103, 'myo-Inositol-hexakisphosphate 3-phosphohydrolase', 'ND', 'Aspergillus niger - Whole'),
        (7104, 'Prunus persica', 'ND', 'Prunus davidiana - Seed'),
        (7105, 'Calcium-potassium salt of (-)-hydroxycitric acid', 'ND', 'Fruit rind'),
        (7106, 'Jonesia asoca', 'ND', 'ND'),
        (7107, 'Serenoa repens', 'ND', 'Fruit(s)'),
        (7108, '(11beta)-11,17,21-Trihydroxypregn-4-ene-3,20-dione', 'ND', 'Hydrocortisone acetate'),
        (7109, 'Histamine dihydrochloride', 'ND', 'Histamine dihydrochloride'),
        (7110, 'Punica granatum', 'Dry', 'Punica granatum, Fruit'),
        (7111, 'Vitamin B12', 'ND', 'Vitamin B12'),
        (7112, 'Ganoderma lucidum', 'ND', 'Spores - broken sporoderm'),
        (7113, 'Trans-Resveratrol', 'ND', 'Reynoutria Japonica - root'),
        (7114, 'Coffea Arabica', 'ND', 'Bean'),
        (7115, 'Frangula purshiana', 'ND', 'Frangula purshiana - Aged bark'),
        (7116, 'Manganese', 'ND', 'Manganese(II) citrate'),
        (7117, 'Mesophyllum superpositum', 'ND', 'Whole'),
        (7118, 'Vitex agnus-castus', 'ND', 'Fruit'),
        (7119, 'Vitamin K1', 'ND', 'Vitamin K1'),
        (7120, 'Melaleuca cajuputi', 'ND', 'Twig leafy'),
        (7121, 'Molybdenum', 'ND', 'Sodium molybdate (VI)'),
        (7122, 'L-Citrulline', 'ND', 'ND'),
        (7123, 'Origanum vulgare', 'ND', 'Leaf'),
        (7124, 'Carica papaya', 'ND', 'Leaf'),
        (7125, 'Hyssopus officinalis', 'ND', 'Flower'),
        (7126, 'Medicago sativa L. (Fabaceae)', 'ND', 'Medicago sativa - Herb top'),
        (7127, 'Curcuma longa', 'Dry', 'Curcuma longa - root'),
        (7128, 'Trifolium pratense', 'ND', 'Herb top'),
        (7129, 'Vitamin A', 'ND', 'Vitamin A palmitate'),
        (7130, 'Copper', 'ND', 'Cupric chloride'),
        (7131, 'Lactobacillus rhamnosus', 'ND', 'HA-111'),
        (7132, 'Acer campestre', 'ND', 'Buds'),
        (7133, 'Chondroitin sulfate', 'ND', 'Bos taurus - cartilage'),
        (7134, 'Chromium', 'ND', 'Chromium (III) nicotinate'),
        (7135, 'Copper', 'ND', 'Cupric acetate'),
        (7136, 'Lycium barbarum', 'ND', 'Fruit'),
        (7137, 'Lecithin', 'ND', 'Glycine max - Seed'),
        (7138, 'Aphanizomenon flos-aquae', 'ND', 'Whole cell'),
        (7139, 'L-alpha-Acetamido-beta-mercaptopropionic acid', 'ND', 'N-Acetyl-L-cysteine'),
        (7140, 'Lutein', 'ND', 'Tagetes erecta - Herb flowering oleoresin'),
        (7141, 'Lactobacillus rhamnosus', 'ND', 'Whole cell - Lactobacillus rhamnosus HA-111'),
        (7142, '(S)-N5-Carbamoylornithine', 'ND', 'Citrulline ethyl ester'),
        (7143, 'Histaminum', 'ND', 'ND'),
        (7144, 'Bifidobacterium animalis subsp. lactis', 'ND', 'BI-07'),
        (7145, 'D-Galacto-L-arabinan', 'ND', 'Larix occidentalis gum'),
        (7146, 'Arthrospira platensis', 'ND', 'Whole'),
        (7147, 'Hydrolyzed collagen', 'ND', 'Fish - skin'),
        (7148, 'L-Alanine', 'ND', 'ND'),
        (7149, '1,3,7-Trimethylxanthine', 'ND', 'Caffeine'),
        (7150, 'Cornus officinalis', 'ND', 'ND'),
        (7151, 'Vitamin D', 'ND', 'Cholecalciferol'),
        (7152, 'Pectin', 'ND', 'Citrus pectin'),
        (7153, 'Iron', 'ND', 'Heme iron polypeptide'),
        (7154, 'Whey protein concentrate', 'ND', 'Bos taurus - Milk'),
        (7155, 'Vitis vinifera', 'Dry', 'Vitis vinifera - Seed'),
        (7156, 'Antimonium crudum', 'ND', 'Antimony trisulfide'),
        (7157, 'Manganese', 'ND', 'Manganese (II) gluconate'),
        (7158, 'Erythrite', 'ND', 'Erythrite'),
        (7159, 'Vaccinium angustifolium', 'ND', 'Vaccinium angustifolium - Fruit'),
        (7160, 'Whey protein isolate', 'ND', 'Whey protein isolate'),
        (7161, 'Bifidobacterium breve', 'ND', 'Whole cell'),
        (7162, '2-Amino-2-deoxy-D-glucose sulfate', 'ND', 'Crab exoskeleton'),
        (7163, 'Paeonia anomala subsp. veitchii', 'ND', 'Paeonia anomala subsp. veitchii - Root'),
        (7164, 'Glycyrrhiza glabra', 'Dry', 'ND'),
        (7165, '2-(3,4-Dihydroxyphenyl)-3,5,7-trihydroxy-4H-1-benzopyran-4-one', 'ND', 'Quercetin dihydrate'),
        (7166, 'Daucus carota', 'ND', 'Root'),
        (7167, 'beta-1,3/1,6-Glucan', 'ND', 'Saccharomyces cerevisiae - Yeast cell wall'),
        (7168, 'Arctium lappa', 'ND', 'Root'),
        (7169, 'N-Acetyl-L-cysteine', 'ND', 'N-Acetyl-L-cysteine'),
        (7170, 'Glycine', 'ND', 'Glycine Sodium Salt'),
        (7171, 'Lactiplantibacillus plantarum', 'ND', 'LP-115'),
        (7172, 'Crocus sativus', 'Dry', 'Stigma'),
        (7173, 'Selenium', 'ND', 'Sodium selenite'),
        (7174, 'Whey Protein Isolate', 'ND', 'Bos taurus (milk)'),
        (7175, 'Arsenicum album', 'ND', 'ND'),
        (7176, '2-Hydroxybenzoic acid', 'ND', 'Salicylic acid'),
        (7177, 'Phosphorus', 'ND', 'Potassium phosphate dibasic'),
        (7178, 'Panax ginseng', 'ND', 'Panax ginseng - root'),
        (7179, 'Valeriana officinalis', 'ND', 'Rhizome(s)'),
        (7180, 'Vitamin E', 'ND', 'RRR-alpha-Tocopherol'),
        (7181, 'Melissa officinalis', 'ND', 'Herb top'),
        (7182, 'Smilax glabra', 'Dry', 'Rhizome'),
        (7183, 'Pancreatic Enzymes', 'ND', 'Sus scrofa - pancreas'),
        (7184, 'Ligusticum sinense cv. chuanxiong', 'ND', 'Ligusticum sinense cv. chuanxiong - Rhizome'),
        (7185, 'Thymus vulgaris', 'Extract Type TBA', 'Leaf'),
        (7186, 'Zinc', 'ND', 'Zinc gluconate'),
        (7187, 'Nickel', 'ND', 'Nickel (II) sulfate'),
        (7188, '1,4-Diaminobutane, N-(3-aminopropyl)-', 'ND', 'Spermidine Trihydrochloride'),
        (7189, 'Actaea racemosa', 'Dry', 'Actaea racemosa - root'),
        (7190, 'Paeonia lactiflora', 'decoction', 'Root'),
        (7191, 'Glycyrrhiza uralensis', 'Dry', 'Rhizome'),
        (7192, 'Ganoderma lucidum', 'Dry', 'Mycelia'),
        (7193, 'Whey Protein Isolate', 'ND', 'Bovine milk'),
        (7194, 'Concentrated desalinated Inland Sea water', 'ND', 'Concentrated desalinated Inland Sea water'),
        (7195, 'Lachesis mutus', 'ND', 'Cattle'),
        (7196, 'Iode', 'ND', 'Iode'),
        (7197, 'Tellurium metallicum', 'ND', 'Tellurium'),
        (7198, 'Glycyrrhiza uralensis', 'ND', 'Root and Rhizome'),
        (7199, 'Methylsulfonylmethane', 'ND', 'ND'),
        (7200, 'Potassium', 'ND', 'Potassium citrate'),
        (7201, 'Morus alba', 'Dry', 'Leaf'),
        (7202, 'Angelica dahurica', 'Dry', 'Root'),
        (7203, 'Myrciaria dubia', 'ND', 'Fruit'),
        (7204, 'Bifidobacterium breve', 'ND', 'Whole cell - Bifidobacterium breve HA-129'),
        (7205, 'Xanthium sibiricum', 'ND', 'Whole plant'),
        (7206, 'Gymnema sylvestre', 'ND', 'Leaf'),
        (7207, 'Wolfiporia extensa', 'Dry', 'Sclerotium'),
        (7208, 'Sus scrofa', 'ND', 'Pig/Sus Capillary tissue'),
        (7209, 'Pollen Extract', 'Dry', 'Secale cereale - anther'),
        (7210, 'Casein micelles', 'ND', 'Bos taurus - Milk'),
        (7211, 'Zinc', 'ND', 'Zinc monomethionine'),
        (7212, 'Echinacea angustifolia', 'ND', 'Whole flowering plant(s)'),
        (7213, 'Triacylglycerol acylhydrolase', 'ND', 'Aspergillus niger - Whole'),
        (7214, 'Oenothera biennis', 'ND', 'Oenothera biennis - Seed'),
        (7215, 'Withania somnifera', 'ND', 'Leaf'),
        (7216, 'Prunus domestica', 'Dry', 'Prunus domestica - Fruit'),
        (7217, 'Vaccinium vitis-idaea', 'ND', 'Young shoots'),
        (7218, 'Angelica pubescens', 'ND', 'Root'),
        (7219, 'Pinellia ternata', 'ND', 'Pinellia ternata - Rhizome'),
        (7220, 'Natrum oxalaceticum', 'ND', 'ND'),
        (7221, 'Tilia Cordata', 'ND', 'Flower'),
        (7222, 'Glucomannan', 'ND', 'Amorphophallus konjac - tuber'),
        (7223, 'Ziziphus jujuba', 'Dry', 'Fruit'),
        (7224, '(S)-2,5-Diaminopentanoic acid', 'ND', 'L-Ornithine Hydrochloride'),
        (7225, 'Mangifera indica', 'ND', 'Fruit'),
        (7226, 'Graphites', 'ND', 'Graphite'),
        (7227, 'Chromium', 'ND', 'ND'),
        (7228, 'Lactobacillus acidophilus', 'ND', 'Whole cell'),
        (7229, 'Mentha x piperita', 'ND', 'Mentha X piperita - leaf'),
        (7230, 'Titanium dioxide', 'ND', 'Titanium dioxide'),
        (7231, '1,3-(1-3,1-4)-beta-D-glucan 3(4)-glucanohydrolase', 'ND', 'Trichoderma longibrachiatum - Whole'),
        (7232, 'Trametes versicolor', 'ND', 'Fruiting body'),
        (7233, 'Lactobacillus plantarum', 'ND', 'Lactobacillus plantarum Rosell-202 - Whole cell'),
        (7234, 'Lacticaseibacillus paracasei', 'ND', 'LAFTIL26'),
        (7235, '3,3'',4'',5,7-Pentahydroxyflavone', 'ND', 'Quercetin'),
        (7236, 'Panax quinquefolius', 'ND', 'Root'),
        (7237, 'Lacticaseibacillus paracasei', 'ND', 'Whole cell'),
        (7238, 'Vitamin D', 'ND', 'Vitamin D'),
        (7239, 'Cinnamomum aromaticum', 'Dry', 'Young branch'),
        (7240, 'Medicago sativa', 'ND', 'Leaf'),
        (7241, 'Vitamin C', 'ND', 'Niacinamide ascorbate'),
        (7242, 'L-5-Hydroxytryptophan', 'ND', 'Griffonia Seed'),
        (7243, 'Niacinamide', 'ND', 'ND'),
        (7244, 'Lactobacillus delbrueckii subsp. bulgaricus', 'ND', 'Whole cell'),
        (7245, 'Lactobacillus rhamnosus', 'ND', 'R-1039'),
        (7246, 'Magnolia officinalis', 'Dry', 'Stem bark'),
        (7247, 'Manganese', 'ND', 'Manganese (II) hydrolyzed vegetable protein (HVP) chelate'),
        (7248, 'Kreosotum', 'ND', 'Creosote obtained from distillation of wood tar'),
        (7249, 'Withania somnifera', 'ND', 'Withania somnifera - root'),
        (7250, 'Iodine', 'ND', 'Ascophyllum nodosum - whole'),
        (7251, 'all-trans-Lycopene', 'ND', 'Lycopene'),
        (7252, 'L-Isoleucine', 'ND', 'L-isoleucine'),
        (7253, 'Lactobacillus rhamnosus', 'ND', 'LR22'),
        (7254, 'Lactobacillus casei', 'ND', 'Lactobacillus casei Rosell-256 - Whole Cell'),
        (7255, 'Glycyrrhiza uralensis', 'ND', 'Glycyrrhiza uralensis, root and rhizome'),
        (7256, 'Allium cepa', 'ND', 'Mature bulb'),
        (7257, 'Althaea officinalis', 'Dry', 'Root'),
        (7258, 'Silybum marianum', 'ND', 'Seed(s)'),
        (7259, 'Bifidobacterium longum subsp. infantis', 'ND', 'Whole cell - Bifidobacterium longum subsp. infantis HA-116'),
        (7260, 'Achyranthes bidentata', 'ND', 'Root'),
        (7261, 'Ligilactobacillus salivarius', 'ND', 'HA-118'),
        (7262, 'Vitamin B6', 'ND', 'Pyridoxal 5''-phosphate'),
        (7263, 'Molybdenum', 'ND', 'Molybdenum amino acid chelate'),
        (7264, 'Platycladus orientalis', 'ND', 'Seed(s)'),
        (7265, 'para-Aminobenzoic acid', 'ND', 'Para-amino benzoic acid'),
        (7266, 'Rehmannia glutinosa', 'decoction', 'Root'),
        (7267, 'Hydrastis canadensis', 'ND', 'Root'),
        (7268, 'Ophiocordyceps sinensis', 'ND', 'Ophiocordyceps sinensis - Whole'),
        (7269, 'Mentha piperita', 'ND', 'Whole plant(s)'),
        (7270, 'Euterpe oleracea', 'ND', 'Fruit'),
        (7271, 'Salix alba', 'ND', 'ND'),
        (7272, 'Thiamine', 'ND', 'ND'),
        (7273, 'Hippoglossus hippoglossus', 'ND', 'Liver oil'),
        (7274, 'Folate', 'ND', 'L-5-Methyltetrahydrofolate, calcium salt'),
        (7275, 'Melissa officinalis', 'ND', 'Herb Top glycerine extract'),
        (7276, '2-Amino-2-deoxy-beta-D-glucopyranose hydrochloride', 'ND', 'Decapods - Exoskeleton'),
        (7277, 'Brassica oleracea var. viridis', 'ND', 'Leaf'),
        (7278, 'Vitamin E', 'ND', 'Glycine Max'),
        (7279, 'Atropinum sulfuricum', 'ND', 'Atropine sulphate'),
        (7280, 'Lycium barbarum', 'ND', 'ND'),
        (7281, 'Hordeum vulgare', 'ND', 'Leaf'),
        (7282, 'Hydrargyrum bichloratum', 'ND', 'Mercuric chloride'),
        (7283, 'Arsenicum album', 'ND', 'Arsenic trioxide'),
        (7284, 'Beta-carotene', 'ND', 'Beta-Carotene'),
        (7285, 'Milk protein isolate', 'ND', 'Bos taurus - Milk'),
        (7286, 'Calcium', 'ND', 'Calcium citrate tetrahydrate'),
        (7287, 'Scutellaria lateriflora', 'ND', 'Aerial parts'),
        (7288, 'Hydrastis canadensis', 'ND', 'Rhizome and root(s)'),
        (7289, 'Fish oil', 'ND', 'ND'),
        (7290, 'Triticum aestivum', 'ND', 'ND'),
        (7291, 'Acorus gramineus', 'Dry', 'Root'),
        (7292, 'Curcuma longa', 'ND', 'Curcuma longa - rhizome'),
        (7293, '2-Amino-2-deoxy-D-glucose sulfate', 'ND', 'Prawn exoskeleton'),
        (7294, 'Pepsin A', 'ND', 'Sus scrofa (stomach)'),
        (7295, 'Passiflora incarnata', 'Dry', 'Passiflora incarnata - Herb top'),
        (7296, 'Bifidobacterium animalis subsp. lactis', 'ND', 'LAFTIB94'),
        (7297, 'Hydrastis canadensis', 'Dry', 'Root and rhizome'),
        (7298, '2-Amino-2-deoxy-D-glucose sulfate', 'ND', 'Aspergillus niger - Whole'),
        (7299, 'Luffa operculata', 'ND', 'Fruit(s)'),
        (7300, 'Citrus aurantium', 'ND', 'Fruit'),
        (7301, 'Thiamine', 'ND', 'Thiamine hydrochloride'),
        (7302, 'Zingiber officinale', 'Dry', 'Rhizome'),
        (7303, 'Serenoa repens', 'Dry', 'ND'),
        (7304, 'Papaver rhoeas', 'ND', 'Flower'),
        (7305, 'Ganoderma lucidum', 'Dry', 'Ganoderma lucidum - mycelia'),
        (7306, 'Rosa roxburghii', 'Dry', 'Whole fruit'),
        (7307, 'Eurycoma longifolia', 'Dry', 'ND'),
        (7308, 'Lepidium meyenii', 'ND', 'Tuber'),
        (7309, 'Iodine', 'ND', 'Potassium iodide'),
        (7310, '4-alpha-D-Glucan glucanohydrolase', 'ND', 'Aspergillus flavus var. oryzae - Whole'),
        (7311, 'Camellia sinensis', 'Dry', 'Leaf'),
        (7312, 'Titanium dioxide', 'ND', 'ND'),
        (7313, 'Papain', 'ND', 'Carica papaya - leaf'),
        (7314, 'Capsicum annuum', 'ND', 'Fruit'),
        (7315, 'Tin', 'ND', 'Stannous chloride'),
        (7316, 'Vitamin B12', 'ND', 'Methylcobalamin'),
        (7317, 'Hibiscus sabdariffa', 'ND', 'Flower'),
        (7318, 'Lactobacillus paracasei', 'ND', 'Whole cell'),
        (7319, 'Vitamin D', 'ND', 'ND'),
        (7320, 'Grifola frondosa', 'Dry', 'Mycelia'),
        (7321, 'L-Threonine', 'ND', 'L-Threonine'),
        (7322, 'Hericium erinaceus', 'Dry', 'ND'),
        (7323, 'Trimethylethanolamine', 'ND', 'ND'),
        (7324, '(S)-N5-Carbamoylornithine', 'ND', 'Citrulline malate'),
        (7325, 'l-Menthol', 'ND', 'l-Menthol'),
        (7326, '3,3'',4'',5,7-Pentahydroxyflavone-3-rutinoside', 'ND', 'Rutin'),
        (7327, 'Apple cider vinegar', 'Dry', 'Malus domestica - Fruit'),
        (7328, 'Spinacia oleracea', 'ND', 'Leaf'),
        (7329, 'Setaria italica', 'Dry', 'ND'),
        (7330, 'trans-Resveratrol', 'ND', 'Reynoutria Japonica - root'),
        (7331, 'Carbo vegetabilis', 'ND', 'Activated charcoal'),
        (7332, 'Magnesia phosphorica', 'ND', 'Magnesia phosphorica'),
        (7333, 'L-isoleucine', 'ND', 'L-isoleucine'),
        (7334, 'Schinopsis quebracho-colorado', 'Dry', 'Stem heartwood'),
        (7335, 'Lactiplantibacillus plantarum', 'ND', 'Whole cell'),
        (7336, 'Capsicum annuum', 'ND', 'Capsicum annuum - fruit'),
        (7337, 'Lactobacillus delbrueckii subsp. bulgaricus', 'ND', 'R-9001'),
        (7338, 'Tamarindus indica', 'ND', 'ND'),
        (7339, 'Brassica oleracea var. italica', 'ND', 'Brassica oleracea var. italica - sprout'),
        (7340, 'Magnolia biondii', 'Dry', 'Flower'),
        (7341, 'Brassica oleracea var. italica', 'ND', 'Aerial parts'),
        (7342, 'Rice Protein', 'ND', 'Rice protein concentrate from Oryza sativa - Seed'),
        (7343, 'Ananas comosus var. comosus', 'ND', 'Fruit'),
        (7344, 'Pediococcus acidilactici', 'ND', 'UL5'),
        (7345, 'Potassium Sulfate', 'ND', 'Potassium sulfate'),
        (7346, 'Angelica dahurica', 'ND', 'Root'),
        (7347, 'Triticum aestivum', 'Dry', 'Seed Germ'),
        (7348, 'Lactobacillus acidophilus', 'ND', 'R-0418'),
        (7349, 'Citrus reticulata', 'Dry', 'Fruit pericarp'),
        (7350, 'Fructooligosaccharides', 'ND', 'Cichorium intybus - Root'),
        (7351, 'Ziziphus jujuba', 'ND', 'Ripe fruit(s)'),
        (7352, 'Triacylglycerol lipase', 'ND', 'Candida rugosa - whole'),
        (7353, 'Prunus mume', 'Dry', 'ND'),
        (7354, 'Sarsaparilla', 'ND', 'Root'),
        (7355, '1-Carboxy-N,N,N-trimethylmethanaminium chloride', 'ND', 'ND'),
        (7356, 'Calcium', 'ND', 'Whey protein concentrate'),
        (7357, 'Benincasa hispida', 'Dry', 'Seed(s)'),
        (7358, 'Rheum officinale', 'Dry', 'Root and rhizome'),
        (7359, 'Streptococcus salivarius subsp. thermophilus - R0083', 'ND', 'Streptococcus salivarius subsp. thermophilus- Whole'),
        (7360, 'Brassica oleracea var. italica', 'ND', 'Whole plant'),
        (7361, 'L-Proline', 'ND', 'Glycine max - Seed'),
        (7362, 'Boric acid', 'ND', 'Boric Acid'),
        (7363, 'beta-galactosidase', 'ND', 'Aspergillus flavus var. oryzae - Whole'),
        (7364, 'Papain', 'ND', 'Carica papaya - fruit'),
        (7365, 'Silicon', 'ND', 'Silicon dioxide'),
        (7366, 'Sus scrofa', 'ND', 'Pig/sus vein'),
        (7367, 'Fish oil', 'ND', 'Salmonids body oil'),
        (7368, 'Medicago sativa', 'Dry', 'Herb top'),
        (7369, 'Chlorella vulgaris', 'ND', 'Chlorella vulgaris - Broken Cell'),
        (7370, 'Vitamin C', 'ND', 'Potassium ascorbate'),
        (7371, 'Ferric Ferrous Oxide', 'ND', 'Magnetite'),
        (7372, 'Kali carbonicum', 'ND', 'Potassium carbonate-anhydrous'),
        (7373, 'Paeonia anomala subsp. veitchii', 'ND', 'Root'),
        (7374, 'Eucalyptus essential oil', 'ND', 'Leaf'),
        (7375, 'Linum usitatissimum', 'ND', 'Linum usitatissimum - Seed'),
        (7376, 'Lepidium meyenii', 'ND', 'Root'),
        (7377, 'Arnica montana', 'ND', 'ND'),
        (7378, '1,2,3-Propanetriol', 'ND', 'Glycerol'),
        (7379, 'Cucumis melo', 'ND', 'Cucumis melo, fruit'),
        (7380, 'Lemna minor', 'ND', 'Whole plant(s)'),
        (7381, 'Biotin', 'ND', 'ND'),
        (7382, 'Indolum', 'ND', 'ND'),
        (7383, 'Withania somnifera', 'Dry', 'Root'),
        (7384, 'Chlorophytum borivilianum', 'ND', 'Root'),
        (7385, 'Zingiber officinale', 'ND', 'Rhizome glycerine extract'),
        (7386, 'Choline', 'ND', 'Choline bitartrate'),
        (7387, 'Pulsatilla', 'ND', 'ND'),
        (7388, 'Urtica dioica', 'ND', 'Herb top'),
        (7389, 'Aminoacetic acid', 'ND', 'Glycine'),
        (7390, 'Codonopsis pilosula', 'Dry', 'Root'),
        (7391, 'trans-Resveratrol', 'ND', 'Vitis vinifera - Fruit'),
        (7392, 'Ligilactobacillus salivarius', 'ND', 'Whole cell'),
        (7393, '(Carboxymethyl)trimethylammonium hydroxide inner salt', 'ND', 'Betaine hydrochloride'),
        (7394, 'Brassica oleracea var. gemmifera', 'ND', 'Leaf bud'),
        (7395, 'Magnesium', 'ND', 'Magnesium bisglycinate'),
        (7396, 'All-trans-lycopene', 'ND', 'ND'),
        (7397, 'Curcuma kwangsiensis', 'Dry', 'ND'),
        (7398, 'Bupleurum chinense', 'Dry', 'Root'),
        (7399, 'L-Glutamine', 'ND', 'L-Glutamine'),
        (7400, '4-(1,3;1,4)-beta-D-Glucan 4-glucanohydrolase', 'ND', 'Whole'),
        (7401, 'Ginkgo biloba', 'ND', 'Leaf extract'),
        (7402, 'Anisomeles indica', 'ND', 'ND'),
        (7403, 'Lactobacillus acidophilus', 'ND', 'LA-14'),
        (7404, 'Ziziphus jujuba', 'ND', 'Ziziphus jujuba - Fruit'),
        (7405, 'Copper', 'ND', 'Copper (II) citrate'),
        (7406, 'Scrophularia ningpoensis', 'Dry', 'Root'),
        (7407, 'Selenium', 'ND', 'Sodium selenate'),
        (7408, 'Hydrolyzed Collagen Type I', 'ND', 'Hydrolyzed collagen'),
        (7409, 'Lablab purpureus', 'ND', 'Seed(s)'),
        (7410, 'Corydalis yanhusuo', 'Dry', 'Tuber'),
        (7411, 'Camellia sinensis', 'Dry', 'Camellia sinensis - leaf'),
        (7412, 'Iron', 'ND', 'Ferrous sulfate'),
        (7413, 'Magnesia sulphurica', 'ND', 'Magnesium sulfate'),
        (7414, 'Curcuma longa', 'ND', 'Curcuma longa - root'),
        (7415, 'Trisodium (2S-trans)-(18-carboxy-20-(carboxymethyl)-13-ethyl-2,3-dihydro-3,7,12,17-tetramethyl-8-vinyl-21H,23H-porphine-2-propionato(5-)-N21,N22,N23,N24)cuprate(3-)', 'ND', 'Chlorophyllin copper complex sodium'),
        (7416, 'Glycine max', 'ND', 'Seed(s)'),
        (7417, 'Platycodon grandiflorus', 'Dry', 'Root'),
        (7418, 'Humulus lupulus', 'Dry', 'Flower'),
        (7419, 'Scutellaria baicalensis', 'Dry', 'Root'),
        (7420, 'Crataegus laevigata', 'Dry', 'Crataegus laevigata - Fruit'),
        (7421, 'Inositol', 'ND', 'Inositol'),
        (7422, 'Panax ginseng', 'ND', 'Root'),
        (7423, 'Schinopsis quebracho-colorado', 'ND', 'Stem heartwood'),
        (7424, 'Vaccinium macrocarpon Aiton (Ericaceae)', 'Dry', 'Vaccinium macrocarpon- Fruit'),
        (7425, 'Commiphora myrrha', 'Dry', 'Stem resin'),
        (7426, 'Sambucus nigra subsp. nigra', 'ND', 'Fruit'),
        (7427, 'Pinellia ternata', 'ND', 'Rhizome'),
        (7428, 'Prunus africana', 'ND', 'Prunus africana - Stem bark'),
        (7429, 'Partially hydrolysed guar gum', 'ND', 'Partially hydrolysed guar gum'),
        (7430, 'Lactobacillus paracasei', 'ND', 'Whole cell - Lactobacillus paracasei HA-274'),
        (7431, 'Chamomile', 'ND', 'Flower glycerine extract'),
        (7432, 'Fallopia japonica', 'ND', 'Fallopia japonica - Root'),
        (7433, '(1E,6E)-1,7-Bis(4-hydroxy-3-methoxyphenyl)-1,6-heptadiene-3,5-dione', 'ND', 'Curcuma longa - rhizome'),
        (7434, 'Potassium', 'ND', 'Potassium citrate monohydrate'),
        (7435, 'Centella asiatica', 'ND', 'Leaf'),
        (7436, 'Aphanizomenon flos-aquae', 'ND', 'Whole'),
        (7437, 'Mentha x piperita', 'Dry', 'Leaf'),
        (7438, 'Rhodiola rosea', 'ND', 'Root extract'),
        (7439, 'Zingiber officinale', 'Dry', 'Zingiber officinale - Rhizome'),
        (7440, 'Eurycoma longifolia', 'Dry', 'Root'),
        (7441, 'Calcium', 'ND', 'Calcium citrate'),
        (7442, 'Vitis Vinifera', 'ND', 'Seed(s)'),
        (7443, 'Vigna umbellata', 'ND', 'Seed(s)'),
        (7444, 'Bifidobacterium bifidum', 'ND', 'Whole cell'),
        (7445, 'Juncus effusus', 'Dry', 'Stem pith'),
        (7446, 'Polygala tenuifolia', 'Dry', 'Root'),
        (7447, 'Iron', 'ND', 'Iron (III) pyrophosphate'),
        (7448, 'Artemisia argyi', 'Dry', 'Leaf'),
        (7449, 'Nelumbo nucifera', 'ND', 'Stamen'),
        (7450, 'Rehmannia glutinosa', 'Dry', 'Tuber'),
        (7451, 'Hyssopus officinalis', 'ND', 'Leaf'),
        (7452, '1-[(2E,4E)-5-(1,3-Benzodioxol-5-yl)-1-oxo-2,4-pentadienyl]piperidine', 'ND', 'Piper nigrum - fruit'),
        (7453, 'Niacin', 'ND', 'Nicotinic acid'),
        (7454, 'Bifidobacterium bifidum', 'ND', 'Whole cell - Bifidobacterium bifidum HA-132'),
        (7455, 'Phyllolobium chinense', 'ND', 'Seed(s)'),
        (7456, 'Bifidobacterium longum subsp. longum', 'ND', 'Whole cell'),
        (7457, '5''-[(3S)-(3-Amino-3-carboxypropyl)methylsulfonio]-5''-deoxyadenosine inner salt', 'ND', 'S-Adenosyl-L-methionine disulfate tosylate'),
        (7458, 'Iodine', 'ND', 'Iodine'),
        (7459, 'Folate', 'ND', 'Folic acid'),
        (7460, 'Fish oil', 'ND', 'Engraulidae - Whole'),
        (7461, 'Lactobacillus rhamnosus', 'ND', '6594'),
        (7462, 'Methyl salicylate', 'ND', 'Gaultheria procumbens'),
        (7463, 'Chromium', 'ND', 'Chromium (III) glutarate'),
        (7464, 'Gardenia jasminoides', 'Dry', 'Fruit'),
        (7465, 'Aletris farinosa', 'ND', 'Root'),
        (7466, 'Vaccinium macrocarpon', 'Dry', 'Fruit'),
        (7467, 'Riboflavin', 'ND', 'Riboflavin 5''-phosphate sodium'),
        (7468, 'Spirulina platensis', 'ND', 'Spirulina platensis - whole'),
        (7469, 'Protease', 'ND', 'Aspergillus flavus var. oryzae - Whole'),
        (7470, 'Tanacetum parthenium', 'ND', 'Herb top'),
        (7471, 'N-(Aminoiminomethyl)-N-methylglycine monohydrate', 'ND', 'Creatine monohydrate'),
        (7472, 'Olea europaea', 'Dry', 'Olea europaea - leaf'),
        (7473, 'Riboflavin', 'ND', 'Riboflavin'),
        (7474, 'Euterpe oleracea', 'ND', 'Euterpe oleracea, fruit'),
        (7475, 'Iodine', 'ND', 'ND'),
        (7476, 'Vitamin B6', 'ND', 'Pyridoxine hydrochloride'),
        (7477, 'Panax quinquefolius', 'Dry', 'Panax quinquefolius root'),
        (7478, 'alpha-D-Galactoside galactohydrolase', 'ND', 'Aspergillus niger - Whole'),
        (7479, 'Calcium caseinate', 'ND', 'Bos taurus - Milk'),
        (7480, '2-(3,4-Dihydroxyphenyl)-3,5,7-trihydroxy-4H-1-benzopyran-4-one', 'ND', 'Quercetin'),
        (7481, 'Atractylodes lancea', 'Dry', 'Rhizome'),
        (7482, 'Chrysanthemum x morifolium', 'ND', 'ND');